#ifndef __KMOCRYPTVERSION_H__
#define __KMOCRYPTVERSION_H__

/* Magic numbers */
#define KMOCRYPT_PACKET_MAGIC_NUM   0x02F595A8
#define KMOCRYPT_PKEY_MAGIC_NUM     0x02F595A9

#endif /*__KMOCRYPTVERSION_H__*/
